import { OBASAssistantSettings } from "src/types";
import { t } from "src/lang/helpers";

export const DEFAULT_SETTINGS: OBASAssistantSettings = {
	updateAPIKey: "",
	updateAPIKeyIsValid: false,
	obasFrameworkFolder: "",
	obasRunningLanguage: "ob",
	userEmail: "",
	userChecked: false,
	newSlideLocationOption: "current",
	assignedNewSlideLocation: "",
	defaultDesign: "none",
	templatesFolder: "",
	demoFolder: "",
	userSlideTemplate: "",
	userChapterTemplate: "",
	userChapterAndPagesTemplate: "",
	userPageTemplate: "",
	userBaseLayoutTemplate: "",
	userTocTemplate: "",
	presenter: "Johnny",
	tagline: "OBAS",
	slogan: t("Keep is simple but elegant"),
	dateFormat: "",
	enableUserTemplates: true,
	customizeSlideFolderName: true,
	addChapterWithSubPages: true,
	presentationPlugin: "slidesExtended",
	updateIDs: {
		style: {
			baseID: "",
			tableID: "",
			viewID: "",
		},
		templates: {
			baseID: "",
			tableID: "",
			viewID: "",
		},
		demo: {
			baseID: "",
			tableID: "",
			viewID: "",
		},
		reveal: {
			baseID: "",
			tableID: "",
			viewID: "",
		},
		revealAS: {
			baseID: "",
			tableID: "",
			viewID: "",
		},
	},
	obasHue: 225,
	obasSaturation: 100,
	obasLightness: 50,
	obasHeadingFont: "sysKaiti",
	obasMainFont: "sysKaiti",
	// 各级标题默认与 Heading 一致
	obasH1Font: "sysKaiti",
	obasH2Font: "sysKaiti",
	obasH3Font: "sysKaiti",
	obasH4Font: "sysKaiti",
	obasH5Font: "sysKaiti",
	obasH6Font: "sysKaiti",
};
